# Services
services:

  # Jenkins Service
  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


# Volumes
volumes:
  jenkins_home: